-- Poin bernomor yang sebelumnya ditulis manual sebagai teks paragraf biasa
-- ("1. ... 2. ... 3. ...") gak punya hanging indent yang benar — kalau
-- barisnya panjang dan nyambung ke baris berikutnya, baris lanjutan itu
-- rata kiri (ketutupan sejajar sama angkanya), gak kayak bullet/nomor list
-- asli yang baris lanjutannya nge-indent ngikut teks di atasnya (dikonfirmasi
-- user 2026-09-10). Dikonversi ke sintaks "- item" (satu per baris, TANPA
-- baris kosong di antaranya) biar otomatis jadi <ol><li> asli lewat
-- parsePasalMarkup — sama persis pola yang udah dipakai spka_ins.

UPDATE dokumen_pasal SET isi = '- Memberikan kuasa kepada Bank Syariah Indonesia Kantor Cabang Pembantu Jakarta Utan Kayu, untuk melakukan BLOKIR SALDO rekening saya sejumlah **Rp{{nominal_blokir}}** selama jangka waktu **{{jangka_waktu_hari}} hari**, terhitung dari tanggal **{{tanggal_mulai_blokir}}** dengan tujuan untuk kepentingan menabung Tabungan Umroh.\n- Memberikan instruksi kepada Bank Syariah Indonesia Kantor Cabang Pembantu Jakarta Utan Kayu, untuk melakukan PENDEBETAN dan sekaligus PEMINDAHBUKUAN sejumlah dana/uang sebesar **Rp{{nominal_blokir}}** yang ada di rekening tersebut di atas kepada **PT Alkhalid Jaya Megah, No. Rekening: 7080660361** untuk keperluan pembelian Paket Ibadah Umroh yang dibuktikan dengan manifest keberangkatan atau visa keberangkatan.\n- Menyatakan tidak akan melakukan penarikan saldo secara pribadi sesuai kesepakatan selama proses menabung Tabungan Umroh.\n- Memberikan Kuasa kepada Bank Syariah Indonesia untuk memberikan informasi saldo kepada pihak yang membutuhkan.\n- Surat Pernyataan Kuasa Blokir dan Instruksi Pendebetan ini tidak dapat saya cabut dan batalkan sesuai kesepakatan dengan Bank Syariah Indonesia.\n- Menyatakan membebaskan Bank Syariah Indonesia dari segala tuntutan hukum yang berlaku berkaitan dengan surat pernyataan ini.'
WHERE dokumen = 'surat_pemblokiran' AND nomor = 2;

UPDATE dokumen_pasal SET isi = '- Mengelola Rekening Pemberi Kuasa dalam layanan BSI Cash Management.\n- Memperoleh informasi saldo (inquiry) dan mutasi yang terdapat dalam Rekening Pemberi Kuasa melalui fitur-fitur yang ada di BSI Cash Management.\n- Melakukan pendebitan dari Rekening Pemberi Kuasa melalui fitur yang ada pada layanan BSI Cash Management.'
WHERE dokumen = 'sk_cif' AND nomor = 3;

UPDATE dokumen_pasal SET isi = 'Sehubungan dengan pemberian kuasa tersebut di atas, dengan ini Pemberi Kuasa menyatakan memberikan persetujuan kepada Bank BSI, termasuk kepada pegawai-pegawainya yang melaksanakan isi Surat Kuasa Kerjasama Multi CIF Pada BSI Cash Management ini untuk:\n\n- Memberikan akses kepada Penerima Kuasa atas Rekening Pemberi Kuasa dan karenanya memberikan persetujuan/kewenangan kepada Bank BSI untuk memberikan dan menyediakan semua data berkaitan dengan Rekening Pemberi Kuasa, yang dapat dibuka, diketahui dan diperoleh Penerima Kuasa pada saat mengakses Rekening, termasuk penyerahan data berupa nama, nomor Rekening Pemberi Kuasa maupun jumlah simpanan/dana pada Rekening, dan karenanya Pemberi Kuasa menyatakan bahwa hal tersebut bukanlah merupakan pelanggaran atas ketentuan rahasia bank sebagaimana diatur dalam Undang-Undang Nomor 10 tahun 1998, tentang Perbankan, berikut segenap peraturan pelaksanaannya.\n- Melakukan pendebitan atas Rekening Pemberi Kuasa untuk keperluan pembayaran biaya yang timbul sehubungan pelaksanaan transaksi melalui layanan BSI Cash Management.\n- Pemberi Kuasa memahami dan menerima serta bertanggung jawab atas segala kerugian dan risiko yang mungkin timbul dikemudian hari sehubungan dengan pelaksanaan tindakan-tindakan sebagaimana dimaksud dalam Surat Kuasa Kerjasama Multi CIF pada BSI Cash Management ini, termasuk atas segala tuntutan, gugatan, dan klaim apapun dan dari pihak manapun, oleh karena itu Pemberi Kuasa setuju untuk menanggung risiko tersebut.'
WHERE dokumen = 'sk_cif' AND nomor = 4;
