-- Seed modul_negara + modul_negara_tier dari costing spreadsheet asli
-- (MED Alliance, Arrayan, Turkey 3 rute). Angka harga_per_pax dalam USD,
-- persis sumber (2 baris Arrayan yang salah ketik hari-nya di source
-- sudah dikoreksi berdasar konteks blok sekitarnya - lihat catatan terpisah).

INSERT INTO modul_negara (jenis_program, kode, nama, mata_uang, pakai_periode, pakai_hotel_star, pakai_city_tour_opsi, urutan, aktif) VALUES ('umroh_plus_dubai', 'dubai_med_alliance', 'Dubai - MED Alliance', 'USD', 0, 0, 0, 0, 1);
SET @m0 = LAST_INSERT_ID();
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 1, 15, 19, 48.0, 72);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 1, 20, 24, 44.0, 73);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 1, 25, 29, 40.0, 74);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 1, 30, 34, 39.0, 75);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 1, 35, 39, 37.0, 76);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 1, 40, NULL, 35.0, 77);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 2, 15, 19, 109.0, 79);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 2, 20, 24, 102.0, 80);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 2, 25, 29, 96.0, 81);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 2, 30, 34, 92.0, 82);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 2, 35, 39, 89.0, 83);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m0, NULL, NULL, NULL, 2, 40, NULL, 86.0, 84);
INSERT INTO biaya_master_item (kelompok, nama, keterangan, harga_default, mata_uang, basis_default, trigger_kunci, modul_negara_id, urutan, aktif) VALUES ('Cost Dubai', 'Dubai - MED Alliance (Paket)', 'Tarif otomatis dari tabel tier modul negara', 0, 'USD', 'jamaah', CONCAT('modul_negara_', @m0), @m0, 0, 1);

INSERT INTO modul_negara (jenis_program, kode, nama, mata_uang, pakai_periode, pakai_hotel_star, pakai_city_tour_opsi, urutan, aktif) VALUES ('umroh_plus_dubai', 'dubai_arrayan', 'Dubai - Arrayan', 'USD', 1, 1, 1, 1, 1);
SET @m1 = LAST_INSERT_ID();
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 10, 14, 69.0, 72);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 15, 19, 64.0, 73);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 20, 24, 52.0, 74);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 25, 29, 47.0, 75);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 30, 34, 43.0, 76);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 35, 39, 40.0, 77);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 40, 44, 39.0, 78);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', NULL, NULL, 1, 45, NULL, 38.0, 79);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 10, 14, 118.0, 83);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 15, 19, 101.0, 84);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 20, 24, 93.0, 85);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 25, 29, 85.0, 86);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 30, 34, 79.0, 87);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 35, 39, 76.0, 88);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 40, 44, 73.0, 89);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, NULL, 2, 45, NULL, 72.0, 90);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 10, 14, 128.0, 96);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 15, 19, 114.0, 97);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 20, 24, 103.0, 98);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 25, 29, 93.0, 99);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 30, 34, 86.0, 100);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 35, 39, 82.0, 101);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 40, 44, 80.0, 102);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, NULL, 2, 45, NULL, 78.0, 103);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 10, 14, 269.0, 109);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 15, 19, 230.0, 110);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 20, 24, 216.0, 111);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 25, 29, 202.0, 112);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 30, 34, 193.0, 113);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 35, 39, 186.0, 114);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 40, 44, 182.0, 115);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 1, 3, 45, NULL, 178.0, 116);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 10, 14, 283.0, 123);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 15, 19, 251.0, 124);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 20, 24, 229.0, 125);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 25, 29, 216.0, 126);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 30, 34, 206.0, 127);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 35, 39, 199.0, 128);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 40, 44, 194.0, 129);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 1, 3, 45, NULL, 191.0, 130);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 10, 14, 369.0, 137);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 15, 19, 313.0, 138);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 20, 24, 297.0, 139);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 25, 29, 277.0, 140);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 30, 34, 264.0, 141);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 35, 39, 253.0, 142);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 40, 44, 246.0, 143);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 3, 2, 3, 45, NULL, 240.0, 144);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 10, 14, 390.0, 151);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 15, 19, 335.0, 152);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 20, 24, 317.0, 153);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 25, 29, 297.0, 154);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 30, 34, 284.0, 155);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 35, 39, 275.0, 156);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 40, 44, 266.0, 157);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '1', 4, 2, 3, 45, NULL, 259.0, 158);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 10, 14, 70.0, 169);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 15, 19, 56.0, 170);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 20, 24, 52.0, 171);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 25, 29, 48.0, 172);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 30, 34, 44.0, 173);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 35, 39, 42.0, 174);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 40, 44, 41.0, 175);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', NULL, NULL, 1, 45, NULL, 40.0, 176);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 10, 14, 146.0, 180);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 15, 19, 126.0, 181);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 20, 24, 115.0, 182);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 25, 29, 109.0, 183);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 30, 34, 107.0, 184);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 35, 39, 104.0, 185);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 40, 44, 102.0, 186);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 2, 45, NULL, 99.0, 187);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 10, 14, 158.0, 193);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 15, 19, 146.0, 194);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 20, 24, 135.0, 195);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 25, 29, 129.0, 196);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 30, 34, 127.0, 197);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 35, 39, 123.0, 198);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 40, 44, 121.0, 199);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 2, 45, NULL, 115.0, 200);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 10, 14, 176.0, 206);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 15, 19, 244.0, 207);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 20, 24, 230.0, 208);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 25, 29, 220.0, 209);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 30, 34, 209.0, 210);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 35, 39, 203.0, 211);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 40, 44, 199.0, 212);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 1, 3, 45, NULL, 198.0, 213);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 10, 14, 309.0, 220);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 15, 19, 279.0, 221);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 20, 24, 255.0, 222);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 25, 29, 244.0, 223);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 30, 34, 231.0, 224);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 35, 39, 226.0, 225);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 40, 44, 222.0, 226);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 1, 3, 45, NULL, 221.0, 227);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 10, 14, 312.0, 234);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 15, 19, 272.0, 235);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 20, 24, 261.0, 236);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 25, 29, 249.0, 237);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 30, 34, 233.0, 238);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 35, 39, 229.0, 239);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 40, 44, 221.0, 240);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, 2, 3, 45, NULL, 218.0, 241);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 10, 14, 339.0, 248);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 15, 19, 307.0, 249);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 20, 24, 286.0, 250);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 25, 29, 273.0, 251);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 30, 34, 256.0, 252);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 35, 39, 252.0, 253);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 40, 44, 244.0, 254);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, 2, 3, 45, NULL, 241.0, 255);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 10, 14, 449.0, 262);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 15, 19, 392.0, 263);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 20, 24, 381.0, 264);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 25, 29, 360.0, 265);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 30, 34, 347.0, 266);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 35, 39, 329.0, 267);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 40, 44, 316.0, 268);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 3, NULL, 4, 45, NULL, 309.0, 269);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 10, 14, 489.0, 276);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 15, 19, 429.0, 277);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 20, 24, 409.0, 278);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 25, 29, 389.0, 279);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 30, 34, 371.0, 280);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 35, 39, 356.0, 281);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 40, 44, 348.0, 282);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m1, '2', 4, NULL, 4, 45, NULL, 343.0, 283);
INSERT INTO biaya_master_item (kelompok, nama, keterangan, harga_default, mata_uang, basis_default, trigger_kunci, modul_negara_id, urutan, aktif) VALUES ('Cost Dubai', 'Dubai - Arrayan (Paket)', 'Tarif otomatis dari tabel tier modul negara', 0, 'USD', 'jamaah', CONCAT('modul_negara_', @m1), @m1, 1, 1);

INSERT INTO modul_negara (jenis_program, kode, nama, mata_uang, pakai_periode, pakai_hotel_star, pakai_city_tour_opsi, urutan, aktif) VALUES ('umroh_plus_turkey', 'turkey_istanbul_bursa', 'Turkey - Istanbul & Bursa', 'USD', 0, 0, 0, 2, 1);
SET @m2 = LAST_INSERT_ID();
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 3, 15, 19, 137.0, 73);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 3, 20, 24, 125.0, 74);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 3, 25, 29, 112.0, 75);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 3, 30, 34, 103.0, 76);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 3, 35, 39, 97.0, 77);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 3, 40, NULL, 92.0, 78);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 4, 15, 19, 195.0, 80);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 4, 20, 24, 179.0, 81);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 4, 25, 29, 166.0, 82);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 4, 30, 34, 155.0, 83);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 4, 35, 39, 146.0, 84);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m2, NULL, NULL, NULL, 4, 40, NULL, 143.0, 85);
INSERT INTO biaya_master_item (kelompok, nama, keterangan, harga_default, mata_uang, basis_default, trigger_kunci, modul_negara_id, urutan, aktif) VALUES ('Cost Turkey', 'Turkey - Istanbul & Bursa (Paket)', 'Tarif otomatis dari tabel tier modul negara', 0, 'USD', 'jamaah', CONCAT('modul_negara_', @m2), @m2, 2, 1);

INSERT INTO modul_negara (jenis_program, kode, nama, mata_uang, pakai_periode, pakai_hotel_star, pakai_city_tour_opsi, urutan, aktif) VALUES ('umroh_plus_turkey', 'turkey_istanbul_cappadocia', 'Turkey - Istanbul & Cappadocia', 'USD', 1, 0, 0, 3, 1);
SET @m3 = LAST_INSERT_ID();
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 5, 15, 19, 231.0, 94);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 5, 20, 24, 205.0, 95);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 5, 25, 29, 185.0, 96);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 5, 30, 34, 171.0, 97);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 5, 35, 39, 165.0, 98);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 5, 40, NULL, 159.0, 99);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 5, 12, 14, 369.0, 101);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 5, 15, 19, 220.0, 102);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 5, 20, 24, 191.0, 103);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 5, 25, 29, 173.0, 104);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 5, 30, 34, 159.0, 105);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 5, 35, 39, 150.0, 106);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 5, 40, NULL, 142.0, 107);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 6, 15, 19, 302.0, 109);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 6, 20, 24, 273.0, 110);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 6, 25, 29, 251.0, 111);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 6, 30, 34, 236.0, 112);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 6, 35, 39, 225.0, 113);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '1', NULL, NULL, 6, 40, NULL, 217.0, 114);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 6, 15, 19, 285.0, 116);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 6, 20, 24, 261.0, 117);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 6, 25, 29, 236.0, 118);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 6, 30, 34, 221.0, 119);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 6, 35, 39, 211.0, 120);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m3, '2', NULL, NULL, 6, 40, NULL, 201.0, 121);
INSERT INTO biaya_master_item (kelompok, nama, keterangan, harga_default, mata_uang, basis_default, trigger_kunci, modul_negara_id, urutan, aktif) VALUES ('Cost Turkey', 'Turkey - Istanbul & Cappadocia (Paket)', 'Tarif otomatis dari tabel tier modul negara', 0, 'USD', 'jamaah', CONCAT('modul_negara_', @m3), @m3, 3, 1);

INSERT INTO modul_negara (jenis_program, kode, nama, mata_uang, pakai_periode, pakai_hotel_star, pakai_city_tour_opsi, urutan, aktif) VALUES ('umroh_plus_turkey', 'turkey_full_turkey', 'Turkey - Full Turkey', 'USD', 1, 0, 0, 4, 1);
SET @m4 = LAST_INSERT_ID();
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 7, 15, 19, 321.0, 130);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 7, 20, 24, 292.0, 131);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 7, 25, 29, 265.0, 132);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 7, 30, 34, 248.0, 133);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 7, 35, 39, 235.0, 134);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 7, 40, NULL, 225.0, 135);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 7, 15, 19, 306.0, 137);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 7, 20, 24, 277.0, 138);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 7, 25, 29, 247.0, 139);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 7, 30, 34, 227.0, 140);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 7, 35, 39, 217.0, 141);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 7, 40, NULL, 207.0, 142);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 8, 15, 19, 399.0, 144);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 8, 20, 24, 362.0, 145);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 8, 25, 29, 337.0, 146);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 8, 30, 34, 317.0, 147);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 8, 35, 39, 303.0, 148);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '1', NULL, NULL, 8, 40, NULL, 292.0, 149);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 8, 15, 19, 375.0, 151);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 8, 20, 24, 342.0, 152);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 8, 25, 29, 313.0, 153);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 8, 30, 34, 293.0, 154);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 8, 35, 39, 282.0, 155);
INSERT INTO modul_negara_tier (modul_negara_id, periode, hotel_star, city_tour_opsi, hari, pax_min, pax_max, harga_per_pax, urutan) VALUES (@m4, '2', NULL, NULL, 8, 40, NULL, 272.0, 156);
INSERT INTO biaya_master_item (kelompok, nama, keterangan, harga_default, mata_uang, basis_default, trigger_kunci, modul_negara_id, urutan, aktif) VALUES ('Cost Turkey', 'Turkey - Full Turkey (Paket)', 'Tarif otomatis dari tabel tier modul negara', 0, 'USD', 'jamaah', CONCAT('modul_negara_', @m4), @m4, 4, 1);
